;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-spacing
        default-indent-new-line
        delete-indentation
        electric-pair-delete-pair
        indent-for-tab-command
        ispell-minor-check
        kill-region
        markdown-outdent-or-delete
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-fill-paragraph
        org-force-self-insert
        org-kill-line
        org-metaright
        org-open-line
        org-self-insert-command
        upcase-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        org-cycle
        smex
        ))
