;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        default-indent-new-line
        delete-indentation
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-open-line
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        org-cycle
        ))
